n1 = int(input())
n2 = int(input())
print('===== Operadores =====')
print('A =',n1) 
print('B =',n2) 
print('Adição =',(n1+n2))
print('Subtração =',(n1-n2))
print('Multiplicação =',(n1*n2))
print('Divisão =',(n1/n2))
print('Resto =',(n1%n2))
print('Exponenciação =',(n1**n2))
print('Oposto de A =',-n1)
print('A é igual a B?',n1==n2)
print('A é diferente de B?',n1!=n2)
print('A é maior que B?',n1>n2)
print('A é menor que B?',n1<n2)
print('A é menor ou igual a B?',n1<=n2)
